variables:
  GIT_CLONE_PATH: /builds/shared/gopath/src/github.com/centny/demoservice/deps/go
  GOROOT: /builds/shared/go
  GOPATH: /builds/shared/gopath/
  GOSUMDB: "off"
  GOPROXY: direct
default:
  image: centos:dev

stages:
  - build

build:
  stage: build
  tags:
    - package
  script:
    - set -e
    - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
    - source /builds/shared/proxy.env
    - cd /builds/shared/gopath/src/github.com/centny/demoservice/deps/go/beec
    - echo "install beec"
    - go install
